services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: evento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  evento-api:
    build:
      context: .
      dockerfile: Evento.Endpoints/Dockerfile
    container_name: evento-api
    depends_on:
      - postgres
    ports:
      - "5164:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production

  angular-app:
    build:
      context: ./Client
    container_name: angular-app
    ports:
      - "4200:80"

volumes:
  pgdata:
